### ISSUE TITLE
Use argument unpacking and direct function invocation

### ISSUE THREAD

**Issue by lstrojny** [friends-of-reactphp/partial#7]
What about a PHP 5.6 version that uses argument unpacking and direct function invocation. Did that for functional-php and it makes the code significantly nicer (and also slightly faster): https://github.com/lstrojny/functional-php/commit/bfd7caee40f7f2cbbb4581e015bcc41cfeca621a

**Comment by WyriHaximus** [comment]
Closing this as this landed with #14
